// The assembled plugin, judged as the thing an install copies. A suite for a PATH rather than a module,
// so it lives here: plugin/ is generated by scripts/assemble-plugin.mjs and reached by Claude Code alone.
//
// The byte diff is check-plugin's own job; what is pinned here is what no diff can see: the copy ANSWERS
// as a hook from its own root, it carries none of the weight the repo-root source used to ship, and the
// gate actually bites on a copy that drifted.
//
// Nothing here ASSEMBLES: the committed plugin/ is what an install copies, so it is what gets judged. A
// test that refreshed it would also refresh it under check-plugin, which runs after the suite and would
// then pass on a working tree whose STAGED copy is stale.

import { describe, it, expect } from "vitest";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const SCRIPT = path.join(REPO, "scripts", "assemble-plugin.mjs");
const PLUGIN = path.join(REPO, "plugin");
const CHECK_FLAG = "--check";
/** What the copy must hold to BE the plugin: manifest, hook wiring, hook, briefing, skill. */
const SHIPPED = [
  ".claude-plugin/plugin.json",
  "hooks/hooks.json",
  "hooks/steering.mjs",
  "agent/steering.md",
  "skills/write-view/SKILL.md",
];
/** The weight the repo-root source used to ship and the copy exists to leave behind. */
const HEAVY = ["node_modules", "dist", "src", "tests", "sandbox", ".claude"];
/** A view name the shipped briefing teaches, proof the payload came from the copy's own file. */
const OWN_TEXT = "@{view:columns}";
const EVENT = "SessionStart";

const run = (...args: string[]) => spawnSync(process.execPath, [SCRIPT, ...args], { encoding: "utf8" });

describe("the assembled plugin", () => {
  it("carries the files an install needs, and none of the repo's weight", () => {
    for (const rel of SHIPPED) expect(fs.existsSync(path.join(PLUGIN, rel)), rel).toBe(true);
    for (const rel of HEAVY) expect(fs.existsSync(path.join(PLUGIN, rel)), rel).toBe(false);
  });

  it("answers as a hook from its own root, on its own briefing", async () => {
    const { steeringPayload, pluginRoot } = await import(
      pathToFileURL(path.join(PLUGIN, "hooks", "steering.mjs")).href
    );
    expect(pluginRoot()).toBe(PLUGIN);
    // An empty project dir keeps the walk from finding an install, so the copy's own file must answer.
    const payload = JSON.parse(await steeringPayload(PLUGIN, { CLAUDE_PROJECT_DIR: PLUGIN }));
    expect(payload.hookSpecificOutput.hookEventName).toBe(EVENT);
    expect(payload.hookSpecificOutput.additionalContext).toContain(OWN_TEXT);
  });

  it("passes its own gate, which BITES on a copy that drifted", () => {
    expect(run(CHECK_FLAG).status).toBe(0);
    const copy = path.join(PLUGIN, "agent", "steering.md");
    const kept = fs.readFileSync(copy);
    fs.writeFileSync(copy, "drifted");
    try {
      const bitten = run(CHECK_FLAG);
      expect(bitten.status).toBe(1);
      expect(bitten.stderr).toContain("differs");
    } finally {
      fs.writeFileSync(copy, kept);
    }
  });
});
